config/routes.rb
Rails.application.routes.draw do

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  devise_for :users
  root "sites#index"
  devise_scope :user do
    get "/admin", to: "devise/sessions#new"
    get "/logout", to: "devise/sessions#destroy", as: :signout
  end

  namespace :api, defaults: { format: :json } do
    resources :products, only: [:index]
  end

  get "/admin/panel"          => "users#admin_panel"
  get "/contact"              => "sites#contact_us"
  get "/location"             => "sites#location"
  get "/faq"                  => "sites#faq"
  get "/terms_and_conditions" => "sites#terms_and_conditions"
 
  resources :contact_forms, only: [:new, :create]
  resources :products, except: [:destroy]
  resources :top_designs, except: [:destroy]
  resources :bottom_designs, except: [:destroy]
  resources :custom_bikinis, except: [:destroy]
  resources :fills, except: [:destroy]
  resources :patterns, except: [:destroy]
  resources :clients, only: [:new, :create, :show]

  get "/happy_customers"      => "clients#happy_customers"
  get "/custom"               => "custom_bikinis#index" 

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  get "/product-orders" => "products#index"

end

app/models/bottom_design.rb
class BottomDesign < ActiveRecord::Base
  has_attached_file :img, :styles => { :medium => "450x450>", :thumb => "100x100>" }, :default_url => "no_pic.png"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :img
  validates :name, presence: true, uniqueness: true
end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :name, presence: true
  has_attached_file :img,
      :styles => { 
        :medium => "450x450>",
        :thumb => "100x100>"
      },
       :default_url => "no_pic.png"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :img

end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true
  attribute :message
  attribute :nickname,  :captcha  => true
  validates :email, presence: true
  validates :message, presence: true

  def headers
    {
      :subject => "Contact: " + URI(request.referer).path,
      :to => "crushalexandrachen@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/custom_bikini.rb
class CustomBikini < ActiveRecord::Base
  # has_one :top_design
  # has_one :bottom_design
end

app/models/fill.rb
class Fill < ActiveRecord::Base
  belongs_to :user
  has_attached_file :img, :styles => { :medium => "450x450>", :thumb => "100x100>"}, :default_url => "no_pic.png"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :img
  validates :name, presence: true, uniqueness: true
  validates_inclusion_of :fill_type, in: Choices['fill']
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  belongs_to :user
  has_attached_file :img,
      :styles => { 
        :medium => "450x450>",
        :thumb => "100x100>"
      },
       :default_url => "no_pic.png"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :img
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
  has_many :order_items

  validates :title, presence: true, length: {maximum: 40}
  # validates :description, presence: true
  validates :user, presence: true
  validates :price, presence: true
  validates :size, presence: true
  has_attached_file :img, :styles => { :medium => "450x450>", :thumb => "100x100>" }, :default_url => "no_pic.png"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :img

  scope :search, -> query { where("lower(title) LIKE ? OR lower(tags) LIKE ? OR lower(description) LIKE ? OR lower(size) LIKE ? OR lower(categories) LIKE ?", 
      "%#{query}%".downcase, "%#{query}%".downcase, "%#{query}%".downcase, "%#{query}%".downcase, "%#{query}%".downcase) }

  def self.recent
    all.order("id DESC")
  end

  # default_scope { where(published: true) }
end

app/models/top_design.rb
class TopDesign < ActiveRecord::Base
  has_attached_file :img, :styles => { :medium => "450x450>", :thumb => "100x100>" }, :default_url => "no_pic.png"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :img
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
  has_many :clients
  has_many :fills
  has_many :patterns
  has_many :top_designs
  has_many :bottom_designs
  
  validates :email, presence: true, format: { with: /.+@.+\..+/i }
  validates :full_name, presence: true, format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ }
 	validate :full_name_length

  def full_name_length
		fullname = full_name.split
		if fullname.size <= 1
			errors.add(:full_name, I18n.t(:full_name_error))
		end
	end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def admin_panel
		if current_user.admin?
			@admin = current_user
      @products = @admin.products.order("updated_at DESC")
      @clients = Client.all.order("updated_at DESC")
      @colors = @admin.fills.order("updated_at DESC").where(fill_type:"Color")
      @patterns = @admin.fills.order("updated_at DESC").where(fill_type:"Pattern")
      @top_designs = @admin.top_designs.order("updated_at DESC")
      @bottom_designs = @admin.bottom_designs.order("updated_at DESC")
		else
			render root_path, notice: "You have to be an administrator"
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/costumers_helper.rb
module CostumersHelper
end

app/helpers/fills_helper.rb
module FillsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/top_designs_helper.rb
module TopDesignsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin_panel.html.erb
<div class="container spacer">
  <div class="row">
    <h1> Admin panel </h1>
    <p><%= link_to t("log_out"), '/logout' %></p>
    <div class="col-sm-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Products</h3>
          <p><%= link_to t("add_product"), new_product_path %></p>
        </div>
        <div class="panel-body admin-listing">
          <% @products.each do |product| %>
            <% if product.published == true %>
              <li><%= image_tag product.img.url(:thumb)%><br>
                ID <%= product.id %> | <%= link_to product.title, product_path(product.id) %> | <%= link_to t("edit_product"), edit_product_path(product.id) %>
              </li> <br>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Unpublished Products</h3>
          <p><%= link_to t("add_product"), new_product_path %></p>
        </div>
        <div class="panel-body admin-listing">
          <% @products.each do |product| %>
            <% if product.published != true %>
              <li><%= image_tag product.img.url(:thumb)%><br>
                ID <%= product.id %> | <%= link_to product.title, product_path(product.id) %> | <%= link_to t("edit_product"), edit_product_path(product.id) %>
              </li> <br>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Clients</h3>
          <p><%= link_to t("add_client"), new_client_path %></p>
        </div>
        <div class="panel-body admin-listing">
          <% @clients.each do |client| %>
            <li><%= image_tag client.img.url(:thumb)%><br>
              ID <%= client.id %> 
            </li> <br>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-sm-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Fills</h3>
          <p><%= link_to t("add_fill"), new_fill_path %></p>
        </div>
        <div class="panel-body admin-listing">
          <% @colors.each do |color| %>
            <li><%= image_tag color.img.url(:thumb)%><br>
              ID <%= color.id %> | <%= link_to color.name, fill_path(color.id) %> | <%= link_to t("edit_fill"), edit_fill_path(color.id) %>
            </li> <br>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-sm-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"> Patterns </h3>
          <p><%= link_to t("add_fill"), new_fill_path %></p>
        </div>
        <div class="panel-body admin-listing">
          <% @patterns.each do |pattern| %>
            <li><%= image_tag pattern.img.url(:thumb)%><br>
              ID <%= pattern.id %> | <%= link_to pattern.name, fill_path(pattern.id) %> | <%= link_to t("edit_fill"), edit_fill_path(pattern.id) %>
            </li> <br>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-sm-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"> Top desings </h3>
          <p><%= link_to t("add_top_design"), new_top_design_path %></p>
        </div>
        <div class="panel-body admin-listing">
          <% @top_designs.each do |top_design| %>
            <li><%= image_tag top_design.img.url(:thumb)%><br>
              ID <%= top_design.id %> | <%= link_to top_design.name, top_design_path(top_design.id) %> | <%= link_to t("edit_top_design"), edit_top_design_path(top_design.id) %>
            </li> <br>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-sm-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"> Bottom desings </h3>
          <p><%= link_to t("add_bottom_design"), new_bottom_design_path %></p>
        </div>
        <div class="panel-body admin-listing">
          <% @bottom_designs.each do |bottom_design| %>
            <li><%= image_tag bottom_design.img.url(:thumb)%><br>
              ID <%= bottom_design.id %> | <%= link_to bottom_design.name, bottom_design_path(bottom_design.id) %> | <%= link_to t("edit_bottom_design"), edit_bottom_design_path(bottom_design.id) %>
            </li> <br>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>